# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - r: devel
      os: osx

    - r: oldrel
      os: linux

    - r: release
      os: linux

    - r: devel
      os: linux

after_success:
  - Rscript -e 'covr::codecov()'
